In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

base_path = "/content/drive/MyDrive/f1_pit_strategy/data/raw/"

lap_times = pd.read_csv(base_path + "lap_times.csv")
pit_stops = pd.read_csv(base_path + "pit_stops.csv")
races = pd.read_csv(base_path + "races.csv")

Mounted at /content/drive

In [ ]:
race_id = 1136
driver_id = 830

driver_laps = lap_times[(lap_times['raceId'] == race_id) &(lap_times['driverId'] == driver_id)].sort_values('lap')
driver_pits = pit_stops[(pit_stops['raceId'] == race_id) &(pit_stops['driverId'] == driver_id)]
driver_pits.head()

       raceId  driverId  stop  lap      time duration  milliseconds
11105    1136       830     1   22  15:34:56   28.198         28198
11118    1136       830     2   41  16:01:54   24.150         24150

In [ ]:
driver_laps_clean = driver_laps[~driver_laps['lap'].isin(driver_pits['lap'])].copy()
driver_laps_clean.head()

        raceId  driverId  lap  position      time  milliseconds
579876    1136       830    1         6  1:30.354         90354
579877    1136       830    2         6  1:26.170         86170
579878    1136       830    3         6  1:25.855         85855
579879    1136       830    4         6  1:25.633         85633
579880    1136       830    5         6  1:25.218         85218

Tyre age = Number of laps after last pit stop

In [ ]:
driver_laps_clean['tyre_age'] = 0
last_pit_lap = 0
pit_laps = sorted(driver_pits['lap'].tolist())

for idx, row in driver_laps_clean.iterrows():
    lap = row['lap']
    if lap > last_pit_lap and pit_laps and lap > pit_laps[0]:
        last_pit_lap = pit_laps.pop(0)
    driver_laps_clean.at[idx, 'tyre_age'] = lap - last_pit_lap
driver_laps_clean[['lap', 'tyre_age']].head(25)

        lap  tyre_age
579876    1         1
579877    2         2
579878    3         3
579879    4         4
579880    5         5
579881    6         6
579882    7         7
579883    8         8
579884    9         9
579885   10        10
579886   11        11
579887   12        12
579888   13        13
579889   14        14
579890   15        15
579891   16        16
579892   17        17
579893   18        18
579894   19        19
579895   20        20
579896   21        21
579898   23         1
579899   24         2
579900   25         3
579901   26         4